# Konfiguracja dla Netlify

[build]
  # Ustawienie base directory na pusty string, aby nadpisać ewentualne
  # błędne ustawienia w interfejsie webowym Netlify.
  base = ""

  # Polecenie do zbudowania aplikacji Angular w trybie produkcyjnym.
  command = "ng build --configuration production"

  # Prawidłowy katalog publikacji, zgodnie z plikiem angular.json.
  # Ponieważ SSR jest wyłączony, nie ma podkatalogu /browser.
  publish = "dist/meal-planner-pwa"

# Kluczowa reguła dla aplikacji typu SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
